language: node_js

notifications:
  email: false

sudo: false

cache: yarn

node_js:
  - '10'

install:
  - yarn

script:
  - yarn build

before_deploy:
  - npm i -g now
deploy:
  # Deploy hasura
  - provider: script
    script: cd hasura && now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
  # Deploy app
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
