version: '3.6'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha27
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ACCESS_KEY: dev
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"hA-LhR.pPv9eR/2V4t~B?7reN@]Y>d+g"}'
    command:
      - graphql-engine
      - serve
      - --enable-console
  blockspot:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
      - 'graphql-engine'
    environment:
      APP_URL: http://localhost:3000
      HASURA_GRAPHQL_ACCESS_KEY: dev
      HASURA_URL: http://graphql-engine:8080
      JWT_SECRET: hA-LhR.pPv9eR/2V4t~B?7reN@]Y>d+g
      PG_CONNECTION_STRING: postgres://postgres:@postgres:5432/postgres
    volumes:
      - .:/app/

volumes:
  ? db_data
